base_images:
  base:
    name: "4.4"
    namespace: ocp
    tag: base
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.13
canonical_go_repository: github.com/openshift/installer
images:
- dockerfile_path: images/installer/Dockerfile.ci
  from: base
  inputs:
    root:
      as:
      - builder
      paths: null
  to: installer
- dockerfile_path: images/installer-artifacts/Dockerfile.rhel
  from: installer
  inputs:
    root:
      as:
      - builder
      paths: null
  to: installer-artifacts
promotion:
  disabled: true
  name: 4.4-private
  namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
  installer:
    limits:
      memory: 9Gi
    requests:
      cpu: "3"
      memory: 5Gi
  installer-artifacts:
    limits:
      memory: 9Gi
    requests:
      cpu: "3"
      memory: 5Gi
tag_specification:
  name: "4.4"
  namespace: ocp
tests:
- as: bm-steps
  commands: ""
  steps:
    cluster_profile: aws
    workflow: baremetal-ds
