base_images:
  base:
    name: ubi
    namespace: ocp
    tag: "9"
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: rhel-9-release-golang-1.21-openshift-4.17
canonical_go_repository: github.com/openshift/ofcir
images:
- dockerfile_literal: |
    FROM base
    USER 0
    RUN dnf install -y podman
  from: base
  to: custom-src
- dockerfile_path: Dockerfile
  to: ofcir
promotion:
  to:
  - name: test
    namespace: ocp-kni
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: podman-test
  commands: sleep 900s
  container:
    from: custom-src
- as: unit
  commands: |
    XDG_CACHE_HOME="/tmp/cache" \
    GOCACHE="/tmp/cache" \
    GOFLAGS="-mod=readonly" \
    make unit-tests
  container:
    from: src
zz_generated_metadata:
  branch: main
  org: openshift-eng
  repo: ofcir
