base_images:
  base:
    name: "4.8"
    namespace: ocp
    tag: base
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  ocp_builder_rhel-8-golang-1.15-openshift-4.6:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-1.15-openshift-4.6
  ocp_builder_rhel-8-golang-1.15-openshift-4.7:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-1.15-openshift-4.7
  ocp_builder_rhel-8-golang-openshift-4.6:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-openshift-4.6
  openshift_release_golang-1.13:
    name: release
    namespace: openshift
    tag: golang-1.13
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.14
canonical_go_repository: github.com/metal3-io/baremetal-operator
images:
- dockerfile_path: Dockerfile.ocp
  from: base
  inputs:
    ocp_builder_rhel-8-golang-1.15-openshift-4.7:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.15-openshift-4.7
  to: baremetal-operator
promotion:
  name: "4.8"
  namespace: ocp
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  name: "4.8"
  namespace: ocp
test_binary_build_commands: |
  set -eo pipefail
  pip3 install yq
tests:
- artifact_dir: /tmp/artifacts
  as: cbo-sync-check
  commands: |
    set -o pipefail
    echo "Fetching cbo bmh crd"
    curl -s https://raw.githubusercontent.com/openshift/cluster-baremetal-operator/master/manifests/0000_31_cluster-baremetal-operator_03_baremetalhost.crd.yaml -o cbo-bmh.yaml
    echo "Converting cbo bmh crd yaml to json"
    jq --version
    yq --version
    yq eval -j cbo-bmh.yaml > cbo-bmh.json
    echo "Fetching bmo bmh crd"
    curl -s https://raw.githubusercontent.com/openshift/baremetal-operator/master/config/crd/bases/metal3.io_baremetalhosts.yaml -o bmo-bmh.yaml
    echo "Converting bmo bmh crd yaml to json"
    yq eval -j bmo-bmh.yaml > bmo-bmh.json
    echo "Checking diff"
    res=$(diff <(jq -S . bmo-bmh.json) <(jq -S . cbo-bmh.json))
    if [ "$res" != "" ]; then
      echo "BMH crd mismatch found"
      echo $res
      exit 1
    fi
  container:
    from: test-bin
- artifact_dir: /tmp/artifacts
  as: unit
  commands: make unit
  container:
    from: src
- artifact_dir: /tmp/artifacts
  as: lint
  commands: export GOLANGCI_LINT_CACHE=/tmp/.cache make lint
  container:
    from: src
- artifact_dir: /tmp/artifacts
  as: e2e-metal-ipi
  steps:
    cluster_profile: packet
    env:
      DEVSCRIPTS_CONFIG: |
        IP_STACK=v4
        NETWORK_TYPE=OpenShiftSDN
    workflow: baremetalds-e2e
- artifact_dir: /tmp/artifacts
  as: e2e-metal-ipi-ovn-ipv6
  steps:
    cluster_profile: packet
    env:
      DEVSCRIPTS_CONFIG: |
        IP_STACK=v6
        NETWORK_TYPE=OVNKubernetes
    workflow: baremetalds-e2e
- artifact_dir: /tmp/artifacts
  as: e2e-metal-ipi-ovn-dualstack
  steps:
    cluster_profile: packet
    env:
      DEVSCRIPTS_CONFIG: |
        IP_STACK=v4v6
        NETWORK_TYPE=OVNKubernetes
    workflow: baremetalds-e2e
- artifact_dir: /tmp/artifacts
  as: e2e-metal-ipi-virtualmedia
  steps:
    cluster_profile: packet
    workflow: baremetalds-e2e-virtualmedia
zz_generated_metadata:
  branch: master
  org: openshift
  repo: baremetal-operator
